export const actions = {
    profile:{
        DATA_FETCHING:"PROFILE_DATA_FETCHING",
        DATA_FETCHED:"PROFILE_DATA_FETCHED",
        DATA_FETCHED_EROR:"PROFILE_DATA_FETCHED_ERROR",
        USER_DATA_EDITED:"PROFILE_USER_DATA_EDITED",
        IMAGE_UPDATED:"PROFILE_IMAGE_UPDATED"
    },
    posts:{
        DATA_FETCHING:"POSTS_DATA_FETCHING",
        DATA_FETCHED:"POSTS_DATA_FETCHED",
        DATA_FETCHED_EROR:"POSTS_DATA_FETCHED_ERROR",
        DATA_EDITED:"POST_DATA_EDITED",
        POST_DELETED:"POST_DATA_DELETED",
        DATA_CREATED:"POST_DATA_CREATED",
    }
}