export const actions = {
    profile:{
        DATA_FETCHING:"PROFILE_DATA_FETCHING",
        DATA_FETCHED:"PROFILE_DATA_FETCHED",
        DATA_FETCHED_EROR:"PROFILE_DATA_FETCHED_ERROR",
        USER_DATA_EDITED:"PROFILE_USER_DATA_EDITED",
        IMAGE_UPDATED:"PROFILE_IMAGE_UPDATED"
    }
}